"""
Integration test — runs the full research graph with mock clients and InMemorySaver.
Verifies: Planner → Searcher → Critic → interrupt → resume → Writer.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from typing import Any

import pytest
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.types import Command

from app.agent.graph import build_research_graph
from app.agent.state import create_initial_state
from app.core import transient_store
from app.models.events import EventIDGenerator, SSEEvent


class _MockLLM:
    def __init__(self):
        self.call_count = 0

    async def generate(self, messages, *, temperature=0.7, max_tokens=4096, response_format=None) -> str:
        self.call_count += 1
        return json.dumps(self._pick_response(messages))

    async def generate_stream(self, messages, *, temperature=0.7, max_tokens=4096) -> AsyncIterator[str]:
        self.call_count += 1
        text = "# Test Report\n\nGenerated by integration test."
        for char in text:
            yield char

    async def generate_structured(self, messages, *, schema, temperature=0.0) -> dict[str, Any]:
        self.call_count += 1
        return self._pick_response(messages)

    def _pick_response(self, messages: list[dict]) -> dict[str, Any]:
        system = messages[0].get("content", "") if messages else ""
        if "planning" in system.lower() or "decompose" in system.lower():
            return {
                "outline": ["Background", "Analysis"],
                "sub_tasks": [
                    {"id": "task_1", "query": "background research"},
                    {"id": "task_2", "query": "detailed analysis"},
                ],
            }
        elif "critic" in system.lower() or "quality" in system.lower():
            return {
                "has_conflicts": False,
                "conflicts": [],
                "missing_aspects": [],
                "confidence_score": 0.9,
                "recommendation": "proceed",
            }
        return {}


class _MockSearch:
    async def search(self, query, *, max_results=5, include_raw_content=False):
        return [
            {"title": f"Result for {query}", "url": f"https://example.com/{query.replace(' ', '-')}", "content": f"Content about {query}", "score": 0.9}
        ]


class _MockVectorStore:
    def __init__(self):
        self.added = []

    async def add_documents(self, documents, metadatas, ids):
        self.added.append({"documents": documents, "metadatas": metadatas, "ids": ids})

    async def query(self, query_text, *, n_results=5, where=None):
        return []

    async def delete(self, ids):
        pass


async def _collect_sse_events(graph, input_or_cmd, config) -> list[SSEEvent]:
    """Run astream and return all SSE events from node outputs."""
    collected: list[SSEEvent] = []
    async for event in graph.astream(input_or_cmd, config=config):
        if "__interrupt__" in event:
            continue
        for node_name, node_output in event.items():
            for sse in node_output.get("_sse_events", []):
                collected.append(sse)
    return collected


@pytest.fixture(autouse=True)
def cleanup():
    yield
    transient_store.unregister("integration-test-id")
    transient_store.unregister("retry-test-id")


@pytest.mark.asyncio
async def test_full_graph_planner_to_writer() -> None:
    """Full graph: Planner → Searcher → Critic → interrupt → resume → Writer."""
    llm = _MockLLM()
    search = _MockSearch()
    vs = _MockVectorStore()
    saver = InMemorySaver()

    research_id = "integration-test-id"
    graph = build_research_graph(llm=llm, search=search, vectorstore=vs, checkpointer=saver)

    id_gen = EventIDGenerator()
    event_queue: asyncio.Queue = asyncio.Queue()
    transient_store.register(research_id, id_gen, event_queue)

    state = create_initial_state(research_id, "test research question")
    config = {"configurable": {"thread_id": research_id}}

    # Phase 1: run until interrupt (human feedback)
    phase1_events = await _collect_sse_events(graph, state, config)

    # Collect queue events (from human_feedback node)
    queue_events: list[SSEEvent] = []
    while not event_queue.empty():
        queue_events.append(await event_queue.get())

    # Verify graph is interrupted
    snapshot = await graph.aget_state(config)
    assert snapshot.next, "Graph should be interrupted at human_feedback"

    all_phase1 = phase1_events + queue_events
    phase1_types = [e.event.value for e in all_phase1]
    assert "phase_change" in phase1_types
    assert "human_input_needed" in phase1_types

    # Phase 2: resume with feedback (re-register transients)
    transient_store.register(research_id, id_gen, asyncio.Queue())

    resume_data = {"feedback": "auto-approved"}
    phase2_events = await _collect_sse_events(graph, Command(resume=resume_data), config)

    # Combine all events
    all_events = all_phase1 + phase2_events

    # Verify phases appeared in correct order
    phase_changes = [
        e.data["phase"]
        for e in all_events
        if e.event.value == "phase_change"
    ]
    assert "planning" in phase_changes
    assert "searching" in phase_changes
    assert "critiquing" in phase_changes
    assert "awaiting_human_input" in phase_changes
    assert "writing" in phase_changes

    planning_idx = phase_changes.index("planning")
    searching_idx = phase_changes.index("searching")
    critiquing_idx = phase_changes.index("critiquing")
    awaiting_idx = phase_changes.index("awaiting_human_input")
    writing_idx = phase_changes.index("writing")
    assert planning_idx < searching_idx < critiquing_idx < awaiting_idx < writing_idx

    # Verify event IDs are unique
    event_ids = [e.data["event_id"] for e in all_events if "event_id" in e.data]
    assert len(set(event_ids)) == len(event_ids), "Event IDs must be unique"

    # Verify LLM called (planner + critic + writer)
    assert llm.call_count >= 3
    assert len(vs.added) >= 1


@pytest.mark.asyncio
async def test_graph_retry_loop() -> None:
    """Critic retries once, then proceeds → interrupt → resume → writer."""

    class _RetryThenPassLLM:
        def __init__(self):
            self.critic_calls = 0

        async def generate(self, messages, *, temperature=0.7, max_tokens=4096, response_format=None):
            return json.dumps(self._pick(messages))

        async def generate_stream(self, messages, *, temperature=0.7, max_tokens=4096):
            text = "# Retry Test Report"
            for c in text:
                yield c

        async def generate_structured(self, messages, *, schema, temperature=0.0):
            return self._pick(messages)

        def _pick(self, messages):
            system = messages[0].get("content", "") if messages else ""
            if "planning" in system.lower() or "decompose" in system.lower():
                return {
                    "outline": ["Section 1"],
                    "sub_tasks": [{"id": "task_1", "query": "topic 1"}],
                }
            elif "critic" in system.lower() or "quality" in system.lower():
                self.critic_calls += 1
                if self.critic_calls == 1:
                    return {
                        "has_conflicts": True,
                        "conflicts": [{"claim_a": "A", "claim_b": "B", "topic": "test"}],
                        "missing_aspects": ["missing topic"],
                        "confidence_score": 0.3,
                        "recommendation": "retry_search",
                    }
                return {
                    "has_conflicts": False,
                    "conflicts": [],
                    "missing_aspects": [],
                    "confidence_score": 0.9,
                    "recommendation": "proceed",
                }
            return {}

    llm = _RetryThenPassLLM()
    search = _MockSearch()
    vs = _MockVectorStore()
    saver = InMemorySaver()

    research_id = "retry-test-id"
    graph = build_research_graph(llm=llm, search=search, vectorstore=vs, checkpointer=saver)

    id_gen = EventIDGenerator()
    event_queue: asyncio.Queue = asyncio.Queue()
    transient_store.register(research_id, id_gen, event_queue)

    state = create_initial_state(research_id, "retry test")
    config = {"configurable": {"thread_id": research_id}}

    # Phase 1: planner → searcher → critic (retry) → searcher → critic (proceed) → interrupt
    phase1_events = await _collect_sse_events(graph, state, config)

    queue_events = []
    while not event_queue.empty():
        queue_events.append(await event_queue.get())

    # Phase 2: resume
    transient_store.register(research_id, id_gen, asyncio.Queue())

    phase2_events = await _collect_sse_events(graph, Command(resume={"feedback": "ok"}), config)

    all_events = phase1_events + queue_events + phase2_events
    phase_changes = [e.data["phase"] for e in all_events if e.event.value == "phase_change"]

    assert phase_changes.count("searching") == 2
    assert phase_changes.count("critiquing") == 2
    assert "awaiting_human_input" in phase_changes
    assert "writing" in phase_changes

    retry_events = [
        e for e in all_events
        if e.event.value == "agent_step" and e.data.get("action") == "retry_triggered"
    ]
    assert len(retry_events) == 1
    assert llm.critic_calls == 2
