"""
Integration test — runs the full research graph with mock clients.
Verifies the complete flow: Planner → Searcher → Critic → HumanFeedback → Writer.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from typing import Any

import pytest

from app.agent.graph import build_research_graph
from app.agent.state import create_initial_state
from app.core import session_registry
from app.models.events import EventIDGenerator, SSEEvent


class _MockLLM:
    """Mock LLM that responds based on the system prompt content."""

    def __init__(self):
        self.call_count = 0

    async def generate(self, messages, *, temperature=0.7, max_tokens=4096, response_format=None) -> str:
        self.call_count += 1
        return json.dumps(self._pick_response(messages))

    async def generate_stream(self, messages, *, temperature=0.7, max_tokens=4096) -> AsyncIterator[str]:
        self.call_count += 1
        text = "# Test Report\n\nGenerated by integration test."
        for char in text:
            yield char

    async def generate_structured(self, messages, *, schema, temperature=0.0) -> dict[str, Any]:
        self.call_count += 1
        return self._pick_response(messages)

    def _pick_response(self, messages: list[dict]) -> dict[str, Any]:
        system = messages[0].get("content", "") if messages else ""
        if "planning" in system.lower() or "decompose" in system.lower():
            return {
                "outline": ["Background", "Analysis"],
                "sub_tasks": [
                    {"id": "task_1", "query": "background research"},
                    {"id": "task_2", "query": "detailed analysis"},
                ],
            }
        elif "critic" in system.lower() or "quality" in system.lower():
            return {
                "has_conflicts": False,
                "conflicts": [],
                "missing_aspects": [],
                "confidence_score": 0.9,
                "recommendation": "proceed",
            }
        return {}


class _MockSearch:
    async def search(self, query, *, max_results=5, include_raw_content=False):
        return [
            {"title": f"Result for {query}", "url": f"https://example.com/{query.replace(' ', '-')}", "content": f"Content about {query}", "score": 0.9}
        ]


class _MockVectorStore:
    def __init__(self):
        self.added = []

    async def add_documents(self, documents, metadatas, ids):
        self.added.append({"documents": documents, "metadatas": metadatas, "ids": ids})

    async def query(self, query_text, *, n_results=5, where=None):
        return []

    async def delete(self, ids):
        pass


@pytest.fixture(autouse=True)
def cleanup():
    yield
    session_registry.remove_session("integration-test-id")


@pytest.mark.asyncio
async def test_full_graph_planner_to_writer() -> None:
    """Run the full graph with auto-approved human feedback."""
    llm = _MockLLM()
    search = _MockSearch()
    vs = _MockVectorStore()

    graph = build_research_graph(llm=llm, search=search, vectorstore=vs)

    state = create_initial_state("integration-test-id", "test research question")
    state["_id_gen"] = EventIDGenerator()
    event_queue: asyncio.Queue[SSEEvent | None] = asyncio.Queue()
    state["_event_queue"] = event_queue

    collected_events: list[SSEEvent] = []

    async def _auto_approve_feedback():
        """Monitors the event queue and auto-approves human feedback."""
        while True:
            await asyncio.sleep(0.05)
            session = session_registry.get_session("integration-test-id")
            feedback_event = session.get("_feedback_event")
            if feedback_event and not feedback_event.is_set():
                session["human_feedback"] = "auto-approved"
                feedback_event.set()
                break

    async def _collect_events():
        """Drain events from the queue."""
        while True:
            ev = await event_queue.get()
            if ev is None:
                break
            collected_events.append(ev)

    async def _run_graph():
        try:
            async for event in graph.astream(state):
                for node_name, node_output in event.items():
                    for sse in node_output.get("_sse_events", []):
                        await event_queue.put(sse)
        finally:
            await event_queue.put(None)

    # Run graph, event collector, and auto-approver concurrently
    approver_task = asyncio.create_task(_auto_approve_feedback())
    collector_task = asyncio.create_task(_collect_events())
    graph_task = asyncio.create_task(_run_graph())

    await graph_task
    await collector_task
    approver_task.cancel()

    # Verify phases appeared in correct order
    phase_changes = [
        e.data["phase"]
        for e in collected_events
        if e.event.value == "phase_change"
    ]

    assert "planning" in phase_changes
    assert "searching" in phase_changes
    assert "critiquing" in phase_changes
    assert "awaiting_human_input" in phase_changes
    assert "writing" in phase_changes

    # Verify ordering
    planning_idx = phase_changes.index("planning")
    searching_idx = phase_changes.index("searching")
    critiquing_idx = phase_changes.index("critiquing")
    awaiting_idx = phase_changes.index("awaiting_human_input")
    writing_idx = phase_changes.index("writing")
    assert planning_idx < searching_idx < critiquing_idx < awaiting_idx < writing_idx

    # Verify event IDs are unique (no duplicates) across all events
    event_ids = [e.data["event_id"] for e in collected_events if "event_id" in e.data]
    assert len(set(event_ids)) == len(event_ids), "Event IDs must be unique"

    # Verify we got report_chunk events
    chunks = [e for e in collected_events if e.event.value == "report_chunk"]
    assert len(chunks) >= 1
    final_chunks = [c for c in chunks if c.data.get("is_final")]
    assert len(final_chunks) == 1

    # Verify LLM was called multiple times (planner + critic + writer)
    assert llm.call_count >= 3

    # Verify vectorstore received search results
    assert len(vs.added) >= 1


@pytest.mark.asyncio
async def test_graph_retry_loop() -> None:
    """Test that the critic retry loop works correctly."""

    call_count = 0

    class _RetryThenPassLLM:
        def __init__(self):
            self.critic_calls = 0

        async def generate(self, messages, *, temperature=0.7, max_tokens=4096, response_format=None):
            return json.dumps(self._pick(messages))

        async def generate_stream(self, messages, *, temperature=0.7, max_tokens=4096):
            text = "# Retry Test Report"
            for c in text:
                yield c

        async def generate_structured(self, messages, *, schema, temperature=0.0):
            return self._pick(messages)

        def _pick(self, messages):
            system = messages[0].get("content", "") if messages else ""
            if "planning" in system.lower() or "decompose" in system.lower():
                return {
                    "outline": ["Section 1"],
                    "sub_tasks": [{"id": "task_1", "query": "topic 1"}],
                }
            elif "critic" in system.lower() or "quality" in system.lower():
                self.critic_calls += 1
                if self.critic_calls == 1:
                    return {
                        "has_conflicts": True,
                        "conflicts": [{"claim_a": "A", "claim_b": "B", "topic": "test"}],
                        "missing_aspects": ["missing topic"],
                        "confidence_score": 0.3,
                        "recommendation": "retry_search",
                    }
                return {
                    "has_conflicts": False,
                    "conflicts": [],
                    "missing_aspects": [],
                    "confidence_score": 0.9,
                    "recommendation": "proceed",
                }
            return {}

    llm = _RetryThenPassLLM()
    search = _MockSearch()
    vs = _MockVectorStore()

    graph = build_research_graph(llm=llm, search=search, vectorstore=vs)

    state = create_initial_state("integration-test-id", "retry test")
    state["_id_gen"] = EventIDGenerator()
    event_queue: asyncio.Queue = asyncio.Queue()
    state["_event_queue"] = event_queue

    collected_events: list[SSEEvent] = []

    async def _auto_approve():
        while True:
            await asyncio.sleep(0.05)
            session = session_registry.get_session("integration-test-id")
            fe = session.get("_feedback_event")
            if fe and not fe.is_set():
                session["human_feedback"] = "ok"
                fe.set()
                break

    async def _collect():
        while True:
            ev = await event_queue.get()
            if ev is None:
                break
            collected_events.append(ev)

    async def _run():
        try:
            async for event in graph.astream(state):
                for _, out in event.items():
                    for sse in out.get("_sse_events", []):
                        await event_queue.put(sse)
        finally:
            await event_queue.put(None)

    approver = asyncio.create_task(_auto_approve())
    collector = asyncio.create_task(_collect())
    runner = asyncio.create_task(_run())

    await runner
    await collector
    approver.cancel()

    phase_changes = [e.data["phase"] for e in collected_events if e.event.value == "phase_change"]

    # Should see: planning, searching, critiquing (retry), searching (again), critiquing (pass), awaiting_human_input, writing
    assert phase_changes.count("searching") == 2
    assert phase_changes.count("critiquing") == 2
    assert "awaiting_human_input" in phase_changes
    assert "writing" in phase_changes

    # Verify retry_triggered event
    retry_events = [
        e for e in collected_events
        if e.event.value == "agent_step" and e.data.get("action") == "retry_triggered"
    ]
    assert len(retry_events) == 1

    assert llm.critic_calls == 2
