"""
Research agent state schema.
ALL fields MUST be JSON-serializable for checkpoint compatibility.
_sse_events is transient (replaced on each node output, not accumulated).
Non-serializable objects (EventIDGenerator, asyncio.Queue) live in transient_store.
"""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, TypedDict

from app.models.events import SSEEvent


def _replace_sse_events(left: list[SSEEvent], right: list[SSEEvent]) -> list[SSEEvent]:
    return right


class ResearchPhase(str, Enum):
    """Valid phases for the research workflow. Used in SSE phase_change events."""

    PLANNING = "planning"
    SEARCHING = "searching"
    CRITIQUING = "critiquing"
    AWAITING_HUMAN_INPUT = "awaiting_human_input"
    WRITING = "writing"
    COMPLETED = "completed"
    ERROR = "error"


class SubTask(TypedDict):
    """A sub-task generated by the Planner node."""

    id: str
    query: str
    status: str  # "pending" | "completed" | "failed"
    result: str | None


class SearchResult(TypedDict):
    """A single search result from the Searcher node."""

    title: str
    url: str
    content: str
    score: float
    sub_task_id: str


class CritiqueResult(TypedDict):
    """Output from the Critic node."""

    has_conflicts: bool
    conflicts: list[dict[str, str]]
    missing_aspects: list[str]
    confidence_score: float
    recommendation: str  # "proceed" | "retry_search" | "refine_plan"


class ResearchState(TypedDict, total=False):
    """
    LangGraph state for the research workflow.

    All fields are JSON-serializable and checkpoint-safe.
    _sse_events uses a replace-reducer (not accumulated across nodes).
    _last_event_id persists the EventIDGenerator counter across interrupt/resume.
    Non-serializable transient objects (id_gen, event_queue) are in transient_store.
    """

    research_id: str
    query: str
    phase: str  # ResearchPhase value
    plan: dict[str, Any]  # {"outline": [...], "sub_tasks": [...]}
    sub_tasks: list[SubTask]
    search_results: list[SearchResult]
    critique: CritiqueResult | None
    retry_count: int
    max_retries: int
    report: str
    sources: list[dict[str, str]]  # [{"title": ..., "url": ..., "used_in": ...}]
    error: str | None
    human_input_requested: bool
    human_feedback: str | None
    messages: list[dict[str, str]]  # agent reasoning trace
    _last_event_id: int
    _sse_events: Annotated[list[SSEEvent], _replace_sse_events]


def create_initial_state(research_id: str, query: str) -> ResearchState:
    """Create a fresh state with all fields initialized to serializable defaults."""
    return ResearchState(
        research_id=research_id,
        query=query,
        phase=ResearchPhase.PLANNING.value,
        plan={},
        sub_tasks=[],
        search_results=[],
        critique=None,
        retry_count=0,
        max_retries=3,
        report="",
        sources=[],
        error=None,
        human_input_requested=False,
        human_feedback=None,
        messages=[],
        _last_event_id=0,
    )
